learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('learning_logs.urls')),    
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name='learning_logs'
urlpatterns = [
    # HP
    path('',views.index, name='index'),

    path('topics/',views.topics, name='topics'),

    path('topics/<int:topic_id>',views.topic, name='topic'),

    path('new_topic/',views.new_topic, name='new_topic'),

    path('new_entry/<int:topic_id>/',views.new_entry, name='new_entry'),

    path('edit_entry/<int:entry_id>/',views.edit_entry, name='edit_entry'),
    
    # path('test/',views.test, name='test'),
    
    path('save_order/', views.save_order, name='save_order'),
    
    # path('load_order/', views.load_order, name='load_order'),
    
    path('weather/',views.weather, name='weather'),
    
    path('delete_city/<city_id>/',views.delete_city, name='delete_city'),
    
    path('weather/<city_id>', views.setPlt, name='setPlt'),
    
    path('recipe/', views.recipe_page, name='recipe_page'),
    
    path('make_recipe/', views.make_recipe, name='make_recipe'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # デフォルトの認証URLを取り込む
    path('',include('django.contrib.auth.urls')),
    
    path('register/',views.register,name='register'),
    
    path('logout_user/',views.logout_user,name='logout_user'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

class Meta:
    verbose_name_plural = 'entries'
    
    def __str__(self):
        return f"{self.text[:25]}..."

class City(models.Model):
    name = models.CharField(max_length=25)
    my_city = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date_added = models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return self.name
class Meta:
    verbose_name_plural = 'cities'

class Order(models.Model):
    my_order = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    order = models.CharField(max_length=20)
    def __list__(self):
        return self.order

learning_logs/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from .models import Topic, Entry, City, Order

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}
        
class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {'name': TextInput(attrs={'class' : 'input', 'placeholder' : 'City Name'}),} 
        

class OrderForm(forms.ModelForm):
    class Meta:
        model   = Order
        fields  = [ 'order' ]
        labels = {'order':''}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry, City, Order
from .forms import TopicForm, EntryForm, CityForm, OrderForm
from django.http import Http404, JsonResponse
from django.conf import settings
import requests, json
from .spotify import *
from .recipe import *
from .settings_secret import *

url = 'https://api.openweathermap.org/data/2.5/weather?q={}&units=metric&lang=ja&appid=' + OPENWEATHER_SECRET_KEY
url_5days = 'https://api.openweathermap.org/data/2.5/forecast?q={}&units=metric&lang=ja&appid=' + OPENWEATHER_SECRET_KEY


def index(request):
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    # ホーム
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    # openweather
    city_weather = []
    cities = City.objects.filter(my_city=request.user).order_by('date_added')
    # spotify
    title = []
    uri = []
    artist, title, uri = get_spotify_ranking(client_id, client_secret)
    zipmusic = zip(artist, title, uri)
    
    if not cities:
        context = {'topics':topics, 'zipmusic':zipmusic}
        return render(request, 'learning_logs/topics.html',context)
    else:
        city = cities[0]
        city_weather = requests.get(url.format(city.name)).json()
        if city_weather['cod'] == '404':
            context = {'topics':topics, 'zipmusic':zipmusic}
            return render(request, 'learning_logs/topics.html',context)
        else:
            weather = {
                'city' : city_weather['name'],
                'temperature' : city_weather['main']['temp'],
                'description' : city_weather['weather'][0]['description'],
                'icon' : city_weather['weather'][0]['icon']
            }
            context = {'topics':topics, 'weather':weather, 'zipmusic':zipmusic}
            return render(request, 'learning_logs/topics.html',context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries,}
    return render(request, 'learning_logs/topic.html',context)

@login_required
def new_topic(request):
    # 
    if request.method != 'POST':
        # 
        form = TopicForm()
    else:
        # POSTでデータが送信されたのでこれを処理
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    # 空または無効のフォームを表示
    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request, topic_id):
    # 
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        # データは送信していないので空のフォーム
        form = EntryForm()
    else:
        # POSTでデータが送信されたのでこれを処理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic',topic_id=topic_id)
    # 空または無効のフォームを表示
    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request, entry_id):
    # 
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    
    if topic.owner != request.user:
        raise Http404    
    if request.method != 'POST':
        # 初回リクエスト時フォームに埋め込まれている
        form = EntryForm(instance=entry)
    else:
        # POSTでデータが送信されたのでこれを処理する
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context = {'entry':entry, 'topic':topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

# @login_required
# def test(request):
    # return render(request, 'learning_logs/test.html')

@login_required
def save_order(request):
    order = request.POST.get('order')
    if request.method != 'POST':
        order = OrderForm()
    else:
        order = OrderForm(request.POST)
        if order.is_valid():
            order.delete()
            new_order = order.save(commit=False)
            new_order.my_order = request.user
            new_order.save()
            print(order)
        else:
            print(order)
        return redirect('learning_logs:topics')
    print(order)
    return redirect(request, 'learning_logs:topics')



# @login_required
# def load_order(request):
#     form = OrderForm()
#     order = Order.objects.all()
#     print(vars(order))
#     context = {'data':order,'form': form}
#     return render(request, 'learning_logs/topics.html', context)

@login_required
def delete_city(request, city_id):
    city = City.objects.get(pk=city_id)
    city.delete()
    return redirect('learning_logs:weather')

@login_required
def weather(request):
    cities = City.objects.filter(my_city=request.user).order_by('name')
    weather_data = []
    weather = {}
    if request.method != 'POST': 
        form = CityForm()
    else:
        form = CityForm(request.POST)
        if form.is_valid():
            new_city = form.save(commit=False)
            new_city.my_city = request.user
            new_city.save()
            return redirect('learning_logs:weather')
        
    form = CityForm()
    
    for city in cities:
        city_weather = requests.get(url.format(city.name)).json() 
        weather = {
            'city' : city,
            'city_name' : city_weather['name'],
            'temperature' : city_weather['main']['temp'],
            'description' : city_weather['weather'][0]['description'],
            'icon' : city_weather['weather'][0]['icon'],
        }
        weather_data.append(weather)
        
    context = {'weather':weather,'weather_data':weather_data,'form':form}
    return render(request, 'learning_logs/weather.html', context)

@login_required
def setPlt(request, city_id):
    url = 'https://api.openweathermap.org/data/2.5/forecast?q={}&units=metric&lang=ja&appid=' + OPENWEATHER_SECRET_KEY
    city = City.objects.get(pk=city_id)
    weather_icon = []
    x = [i*3 for i in range(0, 23)]
    y = []
    for city_num in range(0, 23):
        city_weather = requests.get(url.format(city.name)).json() 
        
        y.append(city_weather["list"][city_num]["main"]["feels_like"])
        weather_icon.append(city_weather["list"][city_num]["weather"][0]["icon"])
        
    context = {'weather_icon':weather_icon, 'x':x, 'y':y}
    return render(request, 'learning_logs/weather_detail.html', context)

@login_required
def make_recipe(request):
    if request.method != 'POST':
        context = {}
        return render(request, 'learning_logs/recipe.html', context)
    else:
        food = request.POST.get('food')
        notemp, df_recipe, recipe_url = get_recipe(recipe_apikey, food)
        if notemp != False:
            context = {}
            return render(request, 'learning_logs/recipe.html', context)
        else:
            zip_recipe = zip(df_recipe['recipeTitle'].to_list(),recipe_url,df_recipe['foodImageUrl'].to_list(),
                        df_recipe['recipeMaterial'].to_list(),df_recipe['recipeCost'].to_list(),
                        df_recipe['recipeIndication'].to_list())
            context = {'zip_recipe':zip_recipe}
            return render(request, 'learning_logs/recipe.html', context)

@login_required
def recipe_page(request):
    context = {}
    return render(request, 'learning_logs/recipe.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="widh=device-width, initial-scale=1,shrink-to-fit=no">
        <title>Style Plan</title>
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>
    <body>

        <nav class="navbar navber-expand-md navbar-light bg-light mb-4 border">
            <nobr><a class="navbar-brand" href="{% url 'learning_logs:index' %}">Style Plan</a><a class="navbar-brand" href="{% url 'learning_logs:topics' %}">ホーム</a></nobr>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" area-expanded="false"  aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">ホーム</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">こんにちは{{ user.username }}さん</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout_user' %}">ログアウト</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">ユーザー登録</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">ログイン</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p><a href ="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

<p>Todo詳細を編集:</p>
<form action="{% url 'learning_logs:edit_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Todo詳細を更新</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
<div class="jumbotron">
    <h3 class="display-4">Style Plan</h3>

    <p class="lead">『一人暮らし初心者』をサポートするアプリ</p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">登録する &raquo;</a>
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}" role="button">ホームへ &raquo;</a>

</div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p><a href ="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

<p>Todo内容を追加:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Todo内容を追加</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>新規To Doを追加:</p>
<form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">To Doを追加</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/recipe.html
{% extends 'learning_logs/base.html' %}
{% block content %}


<style>
    p::before {
        content: "";
        background: #ffc778;
    }
</style>
<html>
<head><p>キーワードから好きなレシピを、『楽天レシピ』で見つけよう！　<a href ='https://recipe.rakuten.co.jp/'>https://recipe.rakuten.co.jp</a></p>
    <h2>食材を入力してみよう</br></h2></span>
    何も入力しないと、ランダムに表示されます
<div class="column is-offset-4 is-4">               
    <form action="{% url 'learning_logs:make_recipe' %}" method="post">
        {% csrf_token %}
        <div class="field has-addons">
        <input type="textbox" name="food">
        <input type="submit" id="button" name="button" value="レシピを検索">
        </div>
    </form>
</div>
</head>
<body>
    <ul>
        {% for recipeTitle, recipe_url,foodImageUrl,recipeMaterial,recipeCost,recipeIndication in zip_recipe %} 

            <div class="jumbotron"><font size="5"><a href="{{ recipe_url }}" >『{{recipeTitle}}』</a></font> <font size="4">←クリックでサイトに移動</font></nobr><div><img src={{foodImageUrl}} width="200" height="200"alt="Image"></div><font size="5">必要なもの</br>{% for Material in recipeMaterial %}<p>{{Material}}</br></p>{% endfor %}</font> <font size="5">コスト: {{recipeCost}} </br> 所要時間： {{recipeIndication}}</font></div>

        {% endfor %}
    </ul> 
</body>
</html>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
<h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
<p><a href="{% url 'learning_logs:new_entry' topic.id %}">新しいTo do詳細を追加</a></p>

{% for entry in entries %}
<div class="card mb-3">
    <h4 class="card-header">
        {{ entry.date_added|date:'Y/m/d H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">To do詳細を編集</a>
        </small>
    </h4>
    <div class="card-body">
        {{ entry.text|linebreaks }}
    </div>
</div>
{% empty %}
<p>このトピックにはまだ記事がありません。</p>
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<select class="form-control" id="sample" onchange="viewChange();">
    <option value="select1">天気</option>
    <option value="select2">To do</option>
    <option value="select3">音楽 週間Top3</option>
    <option value="select4">レシピ作成</option>
    <option value="select5">--</option>
</select>


{% comment %} <div class="container">
    <div class="card mt-5">
        <div id="result_box" class="card-body">
        </div>
    </div>
    <form id="ajax-order" action="{% url 'learning_logs:save_order'%}" method="POST">
        {% csrf_token %}
        <input type="number" id="number1" required>
        <input type="number" id="number2" required>
        <button type="submit" >保存</button>
    </form>
    <div class="result">
    </div>
</div> {% endcomment %}

<script type="text/javascript">

$(function(){
	$("#sortable").sortable({
		axis: "y", 
		"opacity": 0.5,
		"update": function(event,ui){ 
		}
	});

});
function viewChange(){
    if(document.getElementById('sample')){
        id = document.getElementById('sample').value;
        if(id == 'select1'){
            document.getElementById('a').style.display = "";
            document.getElementById('c').style.display = "none";
            document.getElementById('d').style.display = "none";
            document.getElementById('e').style.display = "none";

        }else if(id == 'select2'){
            document.getElementById('a').style.display = "none";
            document.getElementById('c').style.display = "";
            document.getElementById('d').style.display = "none";
            document.getElementById('e').style.display = "none";

        }
        else if(id == 'select3'){
            document.getElementById('a').style.display = "none";
            document.getElementById('c').style.display = "none";
            document.getElementById('d').style.display = "";
            document.getElementById('e').style.display = "none";

        }
        else if(id == 'select4'){
            document.getElementById('a').style.display = "none";
            document.getElementById('c').style.display = "none";
            document.getElementById('d').style.display = "none";
            document.getElementById('e').style.display = "";

        }
        else if(id == 'select5'){
            document.getElementById('a').style.display = "";
            document.getElementById('c').style.display = "";
            document.getElementById('d').style.display = "";
            document.getElementById('e').style.display = "";

        }

    }

window.onload = viewChange;
return id;
}

// ここからajax
//function getCookie(name) {
    {% comment %} var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$.ajaxSetup({
    beforeSend: function (xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
// ここまでajax

$('#ajax-order').on('submit', function(e) {
    id = viewChange;
    e.preventDefault();
    $.ajax({
        'url': '{% url "learning_logs:topics"%}',
        'type': 'POST',
        "dataType": "text",
        'data': {
            'order': id,
        },
    })
    .done(function(response){
    });
}); {% endcomment %}
</script>

<style>
#sortable li{
    list-style-type: none;
    padding: 0px;
}
#sortable  {

}
.handle{
    color: #990;
    padding: 10px;
}
</style>


</head>
<h1>To Do一覧</h1>
    {% for topic in topics %}
    <h3>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h3>
    {% empty %}
    <h3>To Doはまだ作成されていません。</h3>
    {% endfor %}
<h3><a class="btn btn-lg btn-primary" href="{% url 'learning_logs:new_topic' %}" role="button">新規To Doを追加 &raquo;</a></h3>
<body>

<div id="sortable">
    <div class="jumbotron" id="a">
        <h3 class="display-4">
            <i class="handle fas fa-arrows-alt-v">
            </i>
            <div class="container">
                <nobr><font size="8">『{{ weather.city }}』</font><font size="5">の現在</font></nobr>
                {{ weather.description }}<link rel="icon" href="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="Image" width="200" height="200">
            </div>
        </h3>
        <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:weather' %}" role="button">詳細 &raquo;</a>
    </div>

    <div class="jumbotron" id="c">
        <h3 class="display-4">
            <i class="handle fas fa-arrows-alt-v">
            </i>To Do
        </h3>
        <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:new_topic'%}" role="button">追加 &raquo;</a>
    </div>

    <div class="jumbotron" id="d">
        <h1><i class="handle fas fa-arrows-alt-v">
        </i>Spotify 音楽 週間Top3
    <font size="4">クリックでSpotifyに移動</font>
        </h1>
        <h4>
            {% for artist, title, url in zipmusic %}
        <ol>
            <nobr>
                <li>
                    <font size="5"><a>{{ artist }}</a>　<a href="{{ url }}" >『{{ title }}』</a></font>
                </li>
            </nobr>
        </ol>
            {% endfor %}
        </h4>
    </div>

    <div class="jumbotron" id="e">
        <h3 class="display-4">
            <i class="handle fas fa-arrows-alt-v">
            </i>レシピ作成
        </h3>
        <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:make_recipe' %}" role="button">食材を入力 &raquo;</a>
    </div>
    
    {% comment %} <div class="jumbotron" id="b">
        <h3 class="display-4">
            <i class="handle fas fa-arrows-alt-v">
            </i>病気・ケガ
        </h3>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">診断 &raquo;</a>
    </div> {% endcomment %}

</div>
</body>
</html>

{% endblock content %}

learning_logs/templates/learning_logs/weather.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<head>
    <title>天気</title>
</head>
<body>
<div class="column is-offset-4 is-4">               
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="field has-addons">
            <button class="button is-info">
                都市を追加
            </button>
        </div>
    </form>
<ul>
{% for weather in weather_data %}
<div class="card mb-3">
    <h3 class="display-4">{{ weather.city_name }}</h3>
<br>
    <h3 class="display-4">{{ weather.temperature }}° C</h3>
<br> {{ weather.description }}
<figure class="image is-50x50">
    <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="Image">
</figure>
<h3><a href="{% url 'learning_logs:setPlt' weather.city.id %}">3日間の天気を見る（3時間毎）</a></h3>
<a href="{% url 'learning_logs:delete_city' weather.city.id %}" class='btn btn-danger btn-sm'>Delete</a>
</div>
{% empty %}
<p>追加してください</p>
{% endfor %}
</ul>
</div>
</body>
</html>
{% endblock content %}

learning_logs/templates/learning_logs/weather_detail.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<head>3日間の天気
        縦軸が平均気温
        横軸が○時間後
</head>
<body>
<div class="column is-offset-4 is-4">               
<ul>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js" type="text/javascript"></script>
<div class="card mb-3">

<script type="text/javascript">

// ▼グラフの中身
var lineChartData = {
    labels : {{x}},
    datasets : [
        {
            label: "平均気温",
            fillColor : "rgba(0,0,0,0)",
            strokeColor : "rgba(92,220,92,1)",
            pointColor : "rgba(92,220,92,1)",
            pointStrokeColor : "white", 
            pointHighlightFill : "yellow", 
            pointHighlightStroke : "green", 
            data : {{y}}
        },
    ]
}

window.onload = function(){
    var ctx = document.getElementById("graph-area").getContext("2d");
    window.myLine = new Chart(ctx).Line(lineChartData);
}
</script>
<canvas id="graph-area" height="500" width="1010">
    ※表示にはcanvas要素を解釈可能なブラウザが必要です。
</canvas>
</ul>
</div>
{% for icon in weather_icon　%}
<div style="float: left;"><img src="http://openweathermap.org/img/w/{{ icon }}.png" width="40" height="40"alt="Image"></div>
{% endfor %}
</body>
</html>
{% endblock content %}